# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 395)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_res = QtWidgets.QLabel(self.centralwidget)
        self.label_res.setGeometry(QtCore.QRect(0, 0, 430, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_res.setFont(font)
        self.label_res.setStyleSheet("background-color: rgb(122, 122, 122);\n"
"background-color: rgb(188, 188, 188);\n"
"color: rgb(255, 255, 255);")
        self.label_res.setObjectName("label_res")
        self.btn_zero = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zero.setGeometry(QtCore.QRect(0, 305, 165, 90))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_zero.setFont(font)
        self.btn_zero.setStyleSheet("background-color: rgb(94, 46, 22);\n"
"color: rgb(255, 255, 255);")
        self.btn_zero.setObjectName("btn_zero")
        self.btn_rovno = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rovno.setGeometry(QtCore.QRect(165, 305, 165, 90))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_rovno.setFont(font)
        self.btn_rovno.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 85, 0);")
        self.btn_rovno.setObjectName("btn_rovno")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(0, 220, 110, 85))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("background-color: rgb(94, 46, 22);\n"
"color: rgb(255, 255, 255);")
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(110, 220, 110, 85))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet("background-color: rgb(94, 46, 22);\n"
"color: rgb(255, 255, 255);")
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(220, 220, 110, 85))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet("background-color: rgb(94, 46, 22);\n"
"color: rgb(255, 255, 255);")
        self.btn_3.setObjectName("btn_3")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(0, 140, 110, 85))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet("background-color: rgb(94, 46, 22);\n"
"color: rgb(255, 255, 255);")
        self.btn_4.setObjectName("btn_4")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(110, 140, 110, 85))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet("background-color: rgb(94, 46, 22);\n"
"color: rgb(255, 255, 255);")
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(220, 140, 110, 85))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet("background-color: rgb(94, 46, 22);\n"
"color: rgb(255, 255, 255);")
        self.btn_6.setObjectName("btn_6")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(0, 60, 110, 85))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet("background-color: rgb(94, 46, 22);\n"
"color: rgb(255, 255, 255);")
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(110, 60, 110, 85))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet("background-color: rgb(94, 46, 22);\n"
"color: rgb(255, 255, 255);")
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(220, 60, 110, 85))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet("background-color: rgb(94, 46, 22);\n"
"color: rgb(255, 255, 255);")
        self.btn_9.setObjectName("btn_9")
        self.btn_umnog = QtWidgets.QPushButton(self.centralwidget)
        self.btn_umnog.setGeometry(QtCore.QRect(330, 60, 50, 85))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_umnog.setFont(font)
        self.btn_umnog.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 85, 0);")
        self.btn_umnog.setObjectName("btn_umnog")
        self.btn_delen = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delen.setGeometry(QtCore.QRect(330, 140, 50, 85))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_delen.setFont(font)
        self.btn_delen.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 85, 0);")
        self.btn_delen.setObjectName("btn_delen")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(330, 220, 50, 85))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_minus.setFont(font)
        self.btn_minus.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 85, 0);")
        self.btn_minus.setObjectName("btn_minus")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(330, 305, 50, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_plus.setFont(font)
        self.btn_plus.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 85, 0);")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_umnog_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_umnog_2.setGeometry(QtCore.QRect(380, 60, 50, 85))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_umnog_2.setFont(font)
        self.btn_umnog_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 85, 0);")
        self.btn_umnog_2.setObjectName("btn_umnog_2")
        self.btn_umnog_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_umnog_3.setGeometry(QtCore.QRect(380, 140, 50, 85))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_umnog_3.setFont(font)
        self.btn_umnog_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 85, 0);")
        self.btn_umnog_3.setObjectName("btn_umnog_3")
        self.btn_umnog_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_umnog_4.setGeometry(QtCore.QRect(380, 220, 50, 85))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_umnog_4.setFont(font)
        self.btn_umnog_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 85, 0);")
        self.btn_umnog_4.setObjectName("btn_umnog_4")
        self.btn_umnog_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_umnog_5.setGeometry(QtCore.QRect(380, 305, 50, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_umnog_5.setFont(font)
        self.btn_umnog_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 85, 0);")
        self.btn_umnog_5.setObjectName("btn_umnog_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.label_res.setText(_translate("MainWindow", "00"))
        self.btn_zero.setText(_translate("MainWindow", "0"))
        self.btn_rovno.setText(_translate("MainWindow", "="))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_umnog.setText(_translate("MainWindow", "*"))
        self.btn_delen.setText(_translate("MainWindow", "%"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_umnog_2.setText(_translate("MainWindow", "√"))
        self.btn_umnog_3.setText(_translate("MainWindow", "^"))
        self.btn_umnog_4.setText(_translate("MainWindow", "ac"))
        self.btn_umnog_5.setText(_translate("MainWindow", "del"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
